
package frc.lib.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BumpTest = new ChoreoTraj(
	    "BumpTest",
	    OptionalInt.empty(),
	    4.41559,
	    new Pose2d(3.634, 5.909, Rotation2d.fromRadians(0)),
	    new Pose2d(1.587, 4.022, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj BumpToNeutral = new ChoreoTraj(
	    "BumpToNeutral",
	    OptionalInt.empty(),
	    6.03762,
	    new Pose2d(3.643, 6.062, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588))
	);
	public static final ChoreoTraj DepotShootDepot = new ChoreoTraj(
	    "DepotShootDepot",
	    OptionalInt.empty(),
	    3.12376,
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588)),
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588))
	);
	public static final ChoreoTraj DepotShootNeutral1 = new ChoreoTraj(
	    "DepotShootNeutral1",
	    OptionalInt.empty(),
	    5.9607,
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588)),
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588))
	);
	public static final ChoreoTraj DepotShootNeutral2 = new ChoreoTraj(
	    "DepotShootNeutral2",
	    OptionalInt.empty(),
	    6.1045,
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588)),
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588))
	);
	public static final ChoreoTraj DepotShootOutpostShoot = new ChoreoTraj(
	    "DepotShootOutpostShoot",
	    OptionalInt.empty(),
	    3.80358,
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588)),
	    new Pose2d(2.282, 2.272, Rotation2d.fromRadians(0.588))
	);
	public static final ChoreoTraj DepotShoottoTower = new ChoreoTraj(
	    "DepotShoottoTower",
	    OptionalInt.empty(),
	    1.00609,
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.588)),
	    new Pose2d(1.07, 4.916, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj HubtoDepotShoot = new ChoreoTraj(
	    "HubtoDepotShoot",
	    OptionalInt.empty(),
	    4.79146,
	    new Pose2d(3.565, 5.04, Rotation2d.fromRadians(1.571)),
	    new Pose2d(2.282, 5.797, Rotation2d.fromRadians(-0.748))
	);
	public static final ChoreoTraj OutpostShootOutpost = new ChoreoTraj(
	    "OutpostShootOutpost",
	    OptionalInt.empty(),
	    2.94872,
	    new Pose2d(2.282, 2.272, Rotation2d.fromRadians(0.588)),
	    new Pose2d(2.282, 2.272, Rotation2d.fromRadians(0.588))
	);
	public static final ChoreoTraj OutpostShoottoTower = new ChoreoTraj(
	    "OutpostShoottoTower",
	    OptionalInt.empty(),
	    0.92061,
	    new Pose2d(2.282, 2.272, Rotation2d.fromRadians(0.588)),
	    new Pose2d(1.079, 2.593, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj RightOutpostShoot = new ChoreoTraj(
	    "RightOutpostShoot",
	    OptionalInt.empty(),
	    2.78492,
	    new Pose2d(3.643, 2.007, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(2.282, 2.272, Rotation2d.fromRadians(0.588))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("BumpTest", BumpTest),
		Map.entry("BumpToNeutral", BumpToNeutral),
		Map.entry("DepotShootDepot", DepotShootDepot),
		Map.entry("DepotShootNeutral1", DepotShootNeutral1),
		Map.entry("DepotShootNeutral2", DepotShootNeutral2),
		Map.entry("DepotShootOutpostShoot", DepotShootOutpostShoot),
		Map.entry("DepotShoottoTower", DepotShoottoTower),
		Map.entry("HubtoDepotShoot", HubtoDepotShoot),
		Map.entry("OutpostShootOutpost", OutpostShootOutpost),
		Map.entry("OutpostShoottoTower", OutpostShoottoTower),
		Map.entry("RightOutpostShoot", RightOutpostShoot)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
