// spotless:off
package frc.lib.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BumpToNeutral = new ChoreoTraj(
        "BumpToNeutral",
        OptionalInt.empty(),
        4.52759,
        new Pose2d(3.64292, 6.06233, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.48462, 5.45845, Rotation2d.fromRadians(2.23677))
    );
    public static final ChoreoTraj HubtoNeutralShoot = new ChoreoTraj(
        "HubtoNeutralShoot",
        OptionalInt.empty(),
        4.48333,
        new Pose2d(3.56546, 5.03974, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.48462, 5.45845, Rotation2d.fromRadians(2.23677))
    );
    public static final ChoreoTraj NeutralShootToNeutral2 = new ChoreoTraj(
        "NeutralShootToNeutral2",
        OptionalInt.empty(),
        3.69592,
        new Pose2d(3.48462, 5.45845, Rotation2d.fromRadians(2.23677)),
        new Pose2d(3.48462, 5.45845, Rotation2d.fromRadians(2.23677))
    );
    public static final ChoreoTraj NeutralShootHubSweep = new ChoreoTraj(
        "NeutralShootHubSweep",
        OptionalInt.empty(),
        3.96022,
        new Pose2d(3.48462, 5.45845, Rotation2d.fromRadians(2.23677)),
        new Pose2d(3.48462, 5.45845, Rotation2d.fromRadians(2.23677))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("BumpToNeutral", BumpToNeutral),
        Map.entry("HubtoNeutralShoot", HubtoNeutralShoot),
        Map.entry("NeutralShootToNeutral2", NeutralShootToNeutral2),
        Map.entry("NeutralShootHubSweep", NeutralShootHubSweep)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
