// spotless:off
package frc.lib.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj Bump_To_Neutral = new ChoreoTraj(
        "Bump_To_Neutral",
        OptionalInt.empty(),
        6.04593,
        new Pose2d(3.64292, 6.06233, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722))
    );
    public static final ChoreoTraj Bump_To_NeutralSweep = new ChoreoTraj(
        "Bump_To_NeutralSweep",
        OptionalInt.empty(),
        6.58159,
        new Pose2d(3.64292, 6.06233, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722))
    );
    public static final ChoreoTraj Hub_To_Depot = new ChoreoTraj(
        "Hub_To_Depot",
        OptionalInt.empty(),
        5.00052,
        new Pose2d(3.56546, 5.03974, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722))
    );
    public static final ChoreoTraj NeutralShoot_SendToNeutral = new ChoreoTraj(
        "NeutralShoot_SendToNeutral",
        OptionalInt.empty(),
        2.11517,
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722)),
        new Pose2d(7.56669, 5.67501, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj Shoot_To_HubSweep = new ChoreoTraj(
        "Shoot_To_HubSweep",
        OptionalInt.empty(),
        5.79567,
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722)),
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722))
    );
    public static final ChoreoTraj Shoot_To_Neutral = new ChoreoTraj(
        "Shoot_To_Neutral",
        OptionalInt.empty(),
        5.01217,
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722)),
        new Pose2d(3.102, 5.575, Rotation2d.fromRadians(2.30722))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("Bump_To_Neutral", Bump_To_Neutral),
        Map.entry("Bump_To_NeutralSweep", Bump_To_NeutralSweep),
        Map.entry("Hub_To_Depot", Hub_To_Depot),
        Map.entry("NeutralShoot_SendToNeutral", NeutralShoot_SendToNeutral),
        Map.entry("Shoot_To_HubSweep", Shoot_To_HubSweep),
        Map.entry("Shoot_To_Neutral", Shoot_To_Neutral)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
